### ISSUE TITLE
"appsody deploy" does not force the reload of new docker image

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody#261]
**Describe the bug**
Calls of `appsody deploy` after a code change do not cause k8s to reload the pod with new image.

**To Reproduce**
Assuming kubectl config set to the context of a k8s cluster running the appsody operator:

```
# Create application and deploy it
rm -rf /tmp/recreate
mkdir -p /tmp/recreate
cd /tmp/recreate
appsody init nodejs-express
appsody deploy
# Wait for the pod to complete its exection
curl <application url>
Welcome from Appsody!

# Simulate change in application content and deploy again
sed -ibak "s/Hello/Ola/g" app.js
appsody deploy
curl <application url>
```

**Expected behavior**
The "curl" command should display the new application content:
`Ola from Appsody!`

**Actual behaviour**
The application deployed to the k8s cluster still shows:
`Hello from Appsody!`

Since I can see that the second `appsody deploy` created a new application image, I decided to kill the pod to see if it would come back using the new image:
```
kubectl delete pod -l "app.kubernetes.io/name=recreate"
```
and the new pod was, indeed, reloaded with the new image.
```
curl <application url>
Ola from Appsody!
```

**Environment Details (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Not applicable
 - Version: Not applicable

**If applicable please specify:**
 - CLI version: appsody 0.4.0
 - Stack you are using: nodejs-express and java-microprofile
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Screenshots**
Not applicable

**Additional context**
None

**Comment by chilanti** [comment]
Hi Denilson @nastacio  - can I ask you to try one thing for us? Can you run `appsody deploy` with `-t dev.local/<imagename>:<newtag>` the second time? I suspect that the behavior you are observing is due to the fact that the deployment manifest that gets generated and applied by `appsody deploy` is exactly the same in both cases - so the operator would not detect any changes to the `AppsodyApplication`. I am not suggesting that tagging the image is a solution - I'd just like to prove whether this theory holds water. Thanks.

**Comment by nastacio** [comment]
@chilanti , your suspicion is correct: specifying another name for the image with the "-t" parameter caused the pod to restart.

After `appsody deploy` completed, and using the internal kube server inside docker desktopn, I could see the replicateset and the pod being recreated:

```
kubectl get all --all-namespaces | grep recreate | grep -v java









>>> default       pod/recreate-555c64944c-qf9d6                1/1     Running            0          2m36s
default       service/recreate                           NodePort    10.96.111.103    <none>        3000:30332/TCP           3d14h
default       deployment.apps/recreate           1/1     1            1           3d14h
>>> default       replicaset.apps/recreate-555c64944c           1         1         1       2m36s
default       replicaset.apps/recreate-655958ccf            0         0         0       3d14h
default       replicaset.apps/recreate-84779b667b           0         0         0       3m31s
```

**Comment by neeraj-laad** [comment]
Is it acceptable for users to do `appsody deploy delete` and then run `appsody deploy`? 

The inner loop we provide is for local development - run / test / debug. I'm not sure we want the same for deployments.

**Comment by chilanti** [comment]
I agree with @neeraj-laad. There are two ways around this behavior:
1) Running `appsody deploy delete` and then `appsody deploy` again.
2)Tagging the image explicitly, with a new tag every time you `appsody deploy`. 

One alternative would be to add a property to the `AppsodyApplication` CRD - something like a checksum of the image (optional), and have the CLI update the checksum at every `appsody deploy` - but this requires quite a bit of work both on the Operator side and on the CLI side.

**Comment by nastacio** [comment]
I agree that developers would not be pushing to production systems directly from their workstation, iterating through cycles of code changes and `appsody deploy` calls. In that development context, the workaround is acceptable.

At that point, from the developer's perspective, successive calls to `appsody deploy` have different behavior than successive calls to `appsody run`, which is somewhat confusing when we read the online help for `appsody deploy`:

> This command extracts the code from your project, **builds a local Docker image for deployment**,
> generates a deployment manifest (yaml) file if one is not present, **and uses it to deploy your image to Kubernetes**.

Could we consider an additional note in the CLI output for the `deploy` command, checking whether the image timestamp is newer than the deployment yaml file and warning the user about the changes not being effective until the pod is restarted?

**Comment by chilanti** [comment]
We can certainly document the behavior (nobody reads docs) and add a warning as @nastacio suggests - another option would be to have the CLI attempt an `appsody deploy delete` and then `appsody deploy`. I am reluctant to go down that path for a couple of reasons (I don't like deleting stuff without explicit consent and I feel that this is what the operator should do). Thoughts?

**Comment by chilanti** [comment]
I've opened https://github.com/appsody/website/issues/246 to address this.

**Comment by haf-tech** [comment]
@chilanti why is tagging not a solution? Otherwise the usage of a checksum is viable.
And I saw that
`imagePullPolicy: IfNotPresent`
maybe also advisable to change to `Always`?

**Comment by chilanti** [comment]
@haf-tech - tagging is a solution. There are two options:
1) Removing the app and re-deploying
2) Tagging. 
The first has the advantage that one doesn't have to keep tagging the image.
As to the `imagePullPolicy` - my understanding here is that it's the operator that sets it (or - like in this case - doesn't set it, defaulting it to `IfNotPresent`). I am not sure the CRD for `AppsodyApplication` resources supports this field (I've opened https://github.com/appsody/appsody-operator/issues/137).

**Comment by neeraj-laad** [comment]
This should be addressed by new changes to `appsody deploy/build` which will add additional labels to deployment manifest. including timestamps etc and generate a new appsody-config.yaml. This will guarantee that the file is different and will force re-deploy.

**Comment by kylegc** [comment]
@neeraj-laad this isn't fixed yet. Yes it _should_ be fixed by #405 and related work, but I'm going to reopen until it is fixed. That way we make sure to test it. I'll link to the Epic for better organization.

**Comment by debu66er** [comment]
>     1. Running `appsody deploy delete` and then `appsody deploy` again.

My experience is that this option doesn't work. Deploying to OCP 4.2.2 (CRC in my case as local dev environment) it seems some how the image is cached locally by CRI-O (I think that is the container engine used) and it doesn't matter if you delete and deploy again the app. The old image is reused in OCP cluster.

In my case, just using tags fixed the issue.

It would be nice if we have a way to force a imagePullPolicy field with ALWAYS from appsody deploy command. Does it exist such option?

**Comment by kylegc** [comment]
Unfortunately #405 did not fix this issue. It updates the labels and annotations of `app-deploy.yaml` but that was not good enough for the operator to trigger a new deployment.

There are several variables that come into play here:
- The image tag
- The image pull policy (see also https://github.com/appsody/appsody/issues/384)
- The image registry (and ensuring it is pushed)
- The operator updating the deployment
- The deployment environment (minikube, docker for desktop, openshift)

We also need to be conscious that the `app-deploy.yaml` should be production worthy.

Some discussions in slack here talk about using the SHA256 https://appsody.slack.com/archives/CKXDDB4A3/p1571422300043000

@EnriqueL8 would you please test out some of the scenarios so we have a better idea on how to fix this issue?

**Comment by brightzheng100** [comment]
Let me share my experiments/experience:

1. The `appsody deploy delete` and then `appsody deploy --no-build` won't work as of Appsody v0.5.3. And this process will cause downtime so it's also not recommended in production;

2. I tried to add `imagePullPolicy` to `app-deploy.yaml` but unfortunately, I found that the `imagePullPolicy` in generated Deployment was still `IfNotPresent`, not cascaded down, which caused keep using an old `latest` image:

**The `app-deploy.yaml`**
```
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  ...
spec:
  applicationImage: registry:5000/app-backend:latest
  imagePullPolicy: Always
```

Run `appsody deploy delete` and `appsody deploy --no-build` and then check the deployment:

**The Deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
  template:
    ...
    spec:
      containers:
      - image: registry:5000/app-backend:latest
        imagePullPolicy: IfNotPresent
...
```

**Comment by EnriqueL8** [comment]
This issue needs more design: #864 adds a further discussion. Moving to backlog.
